env:
  global:
    - CC_TEST_REPORTER_ID=b93edd1e9ce6ae1e8365666f3601d4044bd3e9af17cc11a74ceb0301b6cc5a8b
language: python
python:
  - "3.6"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install: make deps
script: make test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT